name: 🐛 React Native for macOS Bug Report
description: Report a reproducible bug or regression in React Native for macOS
title: Describe the problem
labels: [bug]
body:
  - type: markdown
    attributes:
      value: |
        Your issue will be triaged by the team according to [this process](https://github.com/microsoft/react-native-macos/wiki/Triage-Process).
  - type: textarea
    validations:
      required: true
    attributes:
      label: Environment
      description: |
        Please fill in all the relevant fields by running these commands in terminal.
        1. `react-native -v`:
        3. `npm ls react-native-macos`:
        4. `node -v`:
        5. `npm -v`:
        6. `yarn --version`<!-- (if you use Yarn) -->:
        7. `xcodebuild -version`:
      value: |
        react-native -v:
        npm ls react-native-macos:
        node -v:
        npm -v:
        yarn --version:
        xcodebuild -version:
      render: markdown
  - type: textarea
    validations:
      required: true
    attributes:
      label: Steps to reproduce the bug
      description: |
        How would you describe your issue to someone who doesn’t know you or your project?
        Try to write a sequence of steps that anybody can repeat to see the issue.
        Be specific! If the bug cannot be reproduced, your issue may be closed.
      placeholder: |
        1. Go to '...'
        2. Click on '....'
  - type: textarea
    attributes:
      label: Expected Behavior
      description: |
        How did you expect your project to behave?
        It’s fine if you’re not sure your understanding is correct.
        Just write down what you thought would happen.
      placeholder: |
        Write what you thought would happen
  - type: textarea
    attributes:
      label: Actual Behavior
      description: |
        Did something go wrong?
        Is something broken, or not behaving as you expected?
        Describe this section in detail, and attach screenshots if possible.
        Don't just say "it doesn't work"!
      placeholder: |
        Write what happened. Add screenshots!
  - type: textarea
    attributes:
      label: Reproducible Demo
      description: |
        Please share a project that reproduces the issue.
        There are three ways to do it:

        - See if the issue is already reproducable within the RNTester app.
          If the issue pertains to a particular Component or API, try the corresponding
          test page in RNTester. 

        - Create a new app using https://snack.expo.io/ and try to reproduce the issue in it.
          This is useful if you roughly know where the problem is, or can’t share the real code.

        - Or, copy your app and remove things until you’re left with the minimal reproducible demo.
          This is useful for finding the root cause. You may then optionally create a Snack.

        This is a good guide to creating bug demos: https://stackoverflow.com/help/mcve
        Once you’re done, copy and paste the link to the Snack or a public GitHub repository below:
      placeholder: |
        Paste the link to an example project and exact instructions to reproduce the issue.
  - type: textarea
    attributes:
      label: Additional context
      description: Write any other additional context that may help in root causing the issue