jobs:
- job: NPMPublishDryRun
  displayName: NPM Publish Dry Run
  pool:
    vmImage: $(VmImageApple)
  timeoutInMinutes: 60
  cancelTimeoutInMinutes: 5
  steps:
    - template: /.ado/templates/npm-publish-steps.yml@self

