jobs:
  - job: react_native_test_app
    displayName: react-native-test-app
    pool:
      vmImage: $(VmImageApple)
    workspace:
      clean: all
    timeoutInMinutes: 60
    cancelTimeoutInMinutes: 5
    steps:
      - template: /.ado/templates/apple-tools-setup.yml@self

      - template: /.ado/templates/verdaccio-publish.yml@self

      - script: |
          git clone --filter=blob:none --progress https://github.com/microsoft/react-native-test-app.git
        displayName: Clone react-native-test-app

      - script: |
          node .ado/scripts/export-versions.mjs
        displayName: Determine react-native version

      - script: |
          npm run set-react-version $(react_native_version) -- --overrides '{ "react-native-macos": "1000.0.0" }'
        displayName: Configure react-native-test-app dependencies
        workingDirectory: react-native-test-app

      - script: |
          set -eo pipefail
          $(Build.Repository.LocalPath)/.ado/scripts/verdaccio.sh configure
          yarn --no-immutable
        displayName: Install npm dependencies
        workingDirectory: react-native-test-app

      - script: |
          yarn build:macos || yarn build:macos
        displayName: Bundle JavaScript
        workingDirectory: react-native-test-app/example

      - script: |
          rm macos/Podfile.lock
          pod install --project-directory=macos
        displayName: Install Pods
        workingDirectory: react-native-test-app/example

      - script: |
          ../scripts/build/xcodebuild.sh macos/Example.xcworkspace build
        displayName: Build x86
        workingDirectory: react-native-test-app/example
        env:
          CCACHE_DISABLE: 1

      - script: |
          ../scripts/build/xcodebuild.sh macos/Example.xcworkspace clean
          ../scripts/build/xcodebuild.sh macos/Example.xcworkspace build ARCHS=arm64
        displayName: Build ARM
        workingDirectory: react-native-test-app/example
        env:
          CCACHE_DISABLE: 1
