jobs:
  - job: JavaScriptPR
    displayName: Javascript PR
    pool:
      vmImage: $(VmImageApple)
    steps:
      - template: /.ado/templates/apple-tools-setup.yml@self

      - script: yarn install
        displayName: Install npm dependencies

      - script: yarn test-ci
        displayName: Test

      - script: yarn flow-check
        displayName: Flow type check

      - script: yarn lint
        displayName: Lint

      - script: yarn format-check
        displayName: Format
