jobs:
  - job: JavaScriptPR
    displayName: Javascript PR
    pool:
      vmImage: $(VmImageApple)
    steps:
    - template: /.ado/templates/apple-tools-setup.yml@self

    - task: CmdLine@2
      displayName: yarn install
      inputs:
        script: yarn install --immutable

    - task: CmdLine@2
      displayName: yarn test-ci [test]
      inputs:
        script: 'yarn test-ci'
    
    - script: 'yarn flow-check'
      displayName: 'yarn flow-check'

    - script: 'yarn lint'
      displayName: 'yarn lint'

    - script: 'yarn format-check'
      displayName: 'yarn format-check'
