# This file defines the Android PR build steps used during the CI loop
name: $(Date:yyyyMMdd).$(Rev:.r)

trigger: none # will disable CI builds entirely

pr:
  branches:
    include:
      - master
      - 0.59-stable
  paths:
    exclude:
      - '*.md'

jobs:
  - job: AndroidRNPR
    displayName: Android React Native PR
    pool:
      vmImage: ubuntu-18.04
    timeoutInMinutes: 90 # how long to run the job before automatically cancelling
    cancelTimeoutInMinutes: 5 # how much time to give 'run always even if cancelled tasks' before killing them
    steps:
      - checkout: self # self represents the repo where the initial Pipelines YAML file was found
        clean: true # whether to fetch clean each time
        # fetchDepth: 2 # the depth of commits to ask Git to fetch
        lfs: false # whether to download Git-LFS files
        submodules: recursive # set to 'true' for a single level of submodules or 'recursive' to get submodules of submodules
        persistCredentials: false # set to 'true' to leave the OAuth token in the Git config after the initial fetch

      - task: UseNode@1
        inputs:
          version: '12.x'

      - template: templates/apple-droid-node-patching.yml
        parameters:
          apply_office_patches: true

      # Install NuGet
      - task: CmdLine@2
        inputs:
          script: mkdir $(System.DefaultWorkingDirectory)/nuget-bin/ && curl -o $(System.DefaultWorkingDirectory)/nuget-bin/nuget.exe https://dist.nuget.org/win-x86-commandline/latest/nuget.exe


      # This is currently required as the command task (strangely) always runs elevated .. 
      # which makes all the files touched by the above patching step unreadable by following non-command tasks without sudo. 
      # This makes all the files readable.
      - task: CmdLine@2
        displayName: chmod
        inputs:
          script: chmod -R +r .

      - task: CmdLine@2
        displayName: "Rename package to react-native"
        inputs:
          script: node .ado/renamePackageForOffice.js

      - task: CmdLine@2
        displayName: npm install
        inputs:
          script: npm install

      - task: CmdLine@2
        displayName: Remove RNTesterApp.android.bundle
        inputs:
          script: rm -f RNTesterApp.android.bundle

      - task: CmdLine@2
        displayName: Create RNTester bundle
        inputs:
          script: node cli.js bundle --entry-file ./RNTester/js/RNTesterApp.android.js --bundle-output RNTesterApp.android.bundle --platform android

      - task: CmdLine@2
        displayName: gradlew installArchives
        inputs:
          script: ./gradlew installArchives -Pparam="excludeLibs"

      - template: templates\prep-android-nuget.yml

      # Very similar to the default pack task .. but appends 'ndk21' to the nuget pack version
      - task: CmdLine@2
        displayName: 'Verify NuGet can be packed'
        inputs:
          script: NDK=ndk`cat ${ANDROID_SDK_ROOT}/ndk-bundle/source.properties 2>&1 | grep Pkg.Revision | awk '{ print $3}' | awk -F. '{ print $1 }'`; mono $(System.DefaultWorkingDirectory)/nuget-bin/nuget.exe pack $(System.DefaultWorkingDirectory)/ReactAndroid/ReactAndroid.nuspec -OutputDirectory $(System.DefaultWorkingDirectory) -Properties buildNumber=$(buildNumber)-$NDK;commitId=$(Build.SourceVersion)

      - task: CmdLine@2
        displayName: gradlew clean
        inputs:
          script: ./gradlew clean