# This file defines the Apple PR build steps used during the CI loop
name: $(Date:yyyyMMdd).$(Rev:.r)

variables:
  - template: variables/vars.yml

trigger: none # will disable CI builds entirely

pr:
  branches:
    include:
      - main
      - '*-stable'
  paths:
    exclude:
      - '*.md'

jobs:
  - job: JavaScriptPR
    displayName: Javascript PR
    pool:
      vmImage: $(VmImageApple)
      demands: ['xcode', 'sh', 'npm']
    steps:
      - template: templates/apple-job-javascript.yml
        parameters:
            slice_name: $(slice_name)
            xcode_version: $(xcode_version)

  - job: ApplePR
    displayName: PR
    strategy:
      matrix:
        'iOS Paper Debug':
          packager_platform: 'ios'
          xcode_sdk: iphonesimulator
          xcode_scheme: 'RNTester'
          xcode_configuration: 'Debug'
          xcode_destination: 'platform=iOS Simulator,OS=latest,name=iPhone 14'
          xcode_actions: 'build test'
          use_fabric: '0'
        'iOS Paper Release':
          packager_platform: 'ios'
          xcode_sdk: iphonesimulator
          xcode_scheme: 'RNTester'
          xcode_configuration: 'Release'
          xcode_destination: 'platform=iOS Simulator,OS=latest,name=iPhone 14'
          xcode_actions: 'build'
          use_fabric: '0'
        'iOS Fabric Debug': 
          packager_platform: 'ios'
          xcode_sdk: iphonesimulator
          xcode_scheme: 'RNTester'
          xcode_configuration: 'Debug'
          xcode_destination: 'platform=iOS Simulator,OS=latest,name=iPhone 14'
          xcode_actions: 'build test'
          use_fabric: '1'
        # Disable failing job
        # 'iOS Fabric Release': 
        #   packager_platform: 'ios'
        #   xcode_sdk: iphonesimulator
        #   xcode_scheme: 'RNTester'
        #   xcode_configuration: 'Release'
        #   xcode_destination: 'platform=iOS Simulator,OS=latest,name=iPhone 14'
        #   xcode_actions: 'build'
        #   use_fabric: '1' 
        'macOS Paper Debug':
          packager_platform: 'macos'
          xcode_sdk: macosx
          xcode_scheme: 'RNTester-macOS'
          xcode_configuration: 'Debug'
          xcode_destination: 'platform=macOS,arch=x86_64'
          xcode_actions: 'build test'
          use_fabric: '0'
        'macOS Paper Release':
          packager_platform: 'macos'
          xcode_sdk: macosx
          xcode_scheme: 'RNTester-macOS'
          xcode_configuration: 'Release'
          xcode_destination: 'platform=macOS,arch=x86_64'
          xcode_actions: 'build'
          use_fabric: '0'
        # Disable failing job
        # 'macOS Fabric Debug':
        #   packager_platform: 'macos'
        #   xcode_sdk: macosx
        #   xcode_scheme: 'RNTester-macOS'
        #   xcode_configuration: 'Debug'
        #   xcode_destination: 'platform=macOS,arch=x86_64'
        #   xcode_actions: 'build test'
        #   use_fabric: '1'
        # 'macOS Fabric Release':
        #   packager_platform: 'macos'
        #   xcode_sdk: macosx
        #   xcode_scheme: 'RNTester-macOS'
        #   xcode_configuration: 'Release'
        #   xcode_destination: 'platform=macOS,arch=x86_64'
        #   xcode_actions: 'build'
        #   use_fabric: '1'
    pool:
      vmImage: $(VmImageApple)
      demands: ['xcode', 'sh', 'npm']
    timeoutInMinutes: 60 # how long to run the job before automatically cancelling
    cancelTimeoutInMinutes: 5 # how much time to give 'run always even if cancelled tasks' before killing them
    steps:
      - template: templates/apple-job-react-native.yml
        parameters:
          packager_platform: $(packager_platform)
          xcode_sdk: $(xcode_sdk)
          xcode_configuration: $(xcode_configuration)
          xcode_scheme: $(xcode_scheme)
          xcode_actions: $(xcode_actions)
          xcode_destination: $(xcode_destination)
          slice_name: $(slice_name)
          xcode_version: $(xcode_version)

  - job: CliInit
    displayName: Verify react-native-macos-init
    strategy:
      matrix:
        MacDebug:
          configuration: Debug
    pool:
      vmImage: $(VmImageApple)
      demands: ['xcode', 'sh', 'npm']
    steps:
      - template: templates/react-native-macos-init.yml
        parameters:
          configuration: $(configuration)
