# This file defines the Apple PR build steps used during the CI loop
name: $(Date:yyyyMMdd).$(Rev:.r)

variables:
  - template: /.ado/variables/vars.yml@self

trigger: none # will disable CI builds entirely

pr:
  branches:
    include:
      - main
      - '*-stable'
  paths:
    exclude:
      - '*.md'

jobs:
  - template: /.ado/jobs/test-javascript.yml@self

  - template: /.ado/jobs/test-react-native-macos-init.yml@self

  - template: /.ado/jobs/npm-publish-dry-run.yml@self

  - template: /.ado/jobs/build-test-rntester.yml@self
