# This file defines the Apple PR build steps used during the CI loop
name: $(Date:yyyyMMdd).$(Rev:.r)

variables:
  - template: variables/vars.yml

trigger: none # will disable CI builds entirely

pr:
  branches:
    include:
      - main
      - '*-stable'
  paths:
    exclude:
      - '*.md'

jobs:
  - job: JavaScriptPR
    displayName: Javascript PR
    pool:
      vmImage: $(VmImageApple)
      demands: ['xcode', 'sh', 'npm']
    steps:
      - template: templates/apple-job-javascript.yml
        parameters:
            slice_name: $(slice_name)
            xcode_version: $(xcode_version)

  - job: ApplePR
    displayName: PR
    strategy:
      matrix:
        'iOS Paper JSC':
          packager_platform: 'ios'
          xcode_sdk: iphonesimulator
          xcode_scheme: 'RNTester'
          xcode_destination: 'platform=iOS Simulator,OS=$(ios_version),name=$(ios_simulator)'
          xcode_extraArgs: '-xcconfig $(Build.Repository.LocalPath)/.ado/xcconfig/debug_overrides.xcconfig'
          new_arch_enabled: '0'
          use_hermes: '0'
        'macOS Paper JSC':
          packager_platform: 'macos'
          xcode_sdk: macosx
          xcode_scheme: 'RNTester-macOS'
          xcode_destination: 'platform=macOS,arch=arm64'
          xcode_extraArgs: '-xcconfig $(Build.Repository.LocalPath)/.ado/xcconfig/debug_overrides.xcconfig'
          new_arch_enabled: '0'
          use_hermes: '0'
        'iOS Fabric JSC':
          packager_platform: 'ios'
          xcode_sdk: iphonesimulator
          xcode_scheme: 'RNTester'
          xcode_destination: 'platform=iOS Simulator,OS=$(ios_version),name=$(ios_simulator)'
          xcode_extraArgs: '-xcconfig $(Build.Repository.LocalPath)/.ado/xcconfig/debug_overrides.xcconfig'
          new_arch_enabled: '1'
          use_hermes: '0'
        'macOS Fabric JSC':
          packager_platform: 'macos'
          xcode_sdk: macosx
          xcode_scheme: 'RNTester-macOS'
          xcode_destination: 'platform=macOS,arch=arm64'
          xcode_extraArgs: '-xcconfig $(Build.Repository.LocalPath)/.ado/xcconfig/debug_overrides.xcconfig'
          new_arch_enabled: '1'
          use_hermes: '0'
        'visionOS Paper JSC':
          packager_platform: 'ios'
          xcode_sdk: xros
          xcode_scheme: 'RNTester-visionOS'
          xcode_extraArgs: '-xcconfig $(Build.Repository.LocalPath)/.ado/xcconfig/debug_overrides.xcconfig'
          new_arch_enabled: '0'
          use_hermes: '0'
        'visionOS Fabric JSC':
          packager_platform: 'ios'
          xcode_sdk: xros
          xcode_scheme: 'RNTester-visionOS'
          xcode_extraArgs: '-xcconfig $(Build.Repository.LocalPath)/.ado/xcconfig/debug_overrides.xcconfig'
          new_arch_enabled: '1'
          use_hermes: '0'
        # Disable Hermes Jobs for now
        # 'iOS Paper Hermes':
        #   packager_platform: 'ios'
        #   xcode_sdk: iphonesimulator
        #   xcode_scheme: 'RNTester'
        #   xcode_destination: 'platform=iOS Simulator,OS=$(ios_version),name=$(ios_simulator)'
        #   xcode_extraArgs: '-xcconfig $(Build.Repository.LocalPath)/.ado/xcconfig/debug_overrides.xcconfig'
        #   new_arch_enabled: '0'
        #   use_hermes: '1'
        # 'macOS Paper Hermes':
        #   packager_platform: 'macos'
        #   xcode_sdk: macosx
        #   xcode_scheme: 'RNTester-macOS'
        #   xcode_destination: 'platform=macOS,arch=arm64'
        #   xcode_extraArgs: '-xcconfig $(Build.Repository.LocalPath)/.ado/xcconfig/debug_overrides.xcconfig'
        #   new_arch_enabled: '0'
        #   use_hermes: '1'
        # 'iOS Fabric Hermes':
        #   packager_platform: 'ios'
        #   xcode_sdk: iphonesimulator
        #   xcode_scheme: 'RNTester'
        #   xcode_extraArgs: '-xcconfig $(Build.Repository.LocalPath)/.ado/xcconfig/debug_overrides.xcconfig'
        #   new_arch_enabled: '1'
        #   use_hermes: '1'
        # 'macOS Fabric Hermes':
        #   packager_platform: 'macos'
        #   xcode_sdk: macosx
        #   xcode_scheme: 'RNTester-macOS'
        #   xcode_extraArgs: '-xcconfig $(Build.Repository.LocalPath)/.ado/xcconfig/debug_overrides.xcconfig'
        #   new_arch_enabled: '1'
        #   use_hermes: '1'
    pool:
      vmImage: $(VmImageApple)
    timeoutInMinutes: 90 # how long to run the job before automatically cancelling
    cancelTimeoutInMinutes: 5 # how much time to give 'run always even if cancelled tasks' before killing them
    steps:
      - template: templates/apple-job-react-native.yml
        parameters:
          packager_platform: $(packager_platform)
          xcode_sdk: $(xcode_sdk)
          xcode_scheme: $(xcode_scheme)
          xcode_actions: $(xcode_actions)
          slice_name: $(slice_name)
          xcode_version: $(xcode_version)
          xcode_extraArgs: $(xcode_extraArgs)

  - job: CliInit
    displayName: Verify react-native-macos-init
    strategy:
      matrix:
        MacDebug:
          configuration: Debug
    pool:
      vmImage: $(VmImageApple)
      demands: ['xcode', 'sh', 'npm']
    steps:
      - template: templates/react-native-macos-init.yml
        parameters:
          configuration: $(configuration)

  - job: NPMPublishDryRun
    displayName: NPM Publish Dry Run
    pool:
      vmImage: $(VmImageApple)
    timeoutInMinutes: 60 # how long to run the job before automatically cancelling
    cancelTimeoutInMinutes: 5 # how much time to give 'run always even if cancelled tasks' before killing them
    steps:
      - checkout: self # self represents the repo where the initial Pipelines YAML file was found
        clean: true # whether to fetch clean each time
        # fetchDepth: 2 # the depth of commits to ask Git to fetch
        lfs: false # whether to download Git-LFS files
        submodules: recursive # set to 'true' for a single level of submodules or 'recursive' to get submodules of submodules
        persistCredentials: true # set to 'true' to leave the OAuth token in the Git config after the initial fetch

      - template: templates/apple-job-publish.yml
        parameters:
          build_type: 'dry-run'
