# This file defines the build steps to publish a release
name: $(Date:yyyyMMdd).$(Rev:.r)

trigger: 
  batch: true
  branches:
    include:
      - master
      - fb59merge
      - fabric
  paths:
    exclude:
      - package.json

pr: none

jobs:
  - job: RNGithubPublish
    displayName: React-Native GitHub Publish
    pool:
      name: OE Standard Pool
      demands: ['Agent.OS -equals Windows_NT', 'ANDROID_NDK', 'OnPrem -equals False']
    timeoutInMinutes: 90 # how long to run the job before automatically cancelling
    cancelTimeoutInMinutes: 5 # how much time to give 'run always even if cancelled tasks' before killing them
    steps:
      - checkout: self # self represents the repo where the initial Pipelines YAML file was found
        clean: true # whether to fetch clean each time
        fetchDepth: 2 # the depth of commits to ask Git to fetch
        lfs: false # whether to download Git-LFS files
        submodules: recursive # set to 'true' for a single level of submodules or 'recursive' to get submodules of submodules
        persistCredentials: true # set to 'true' to leave the OAuth token in the Git config after the initial fetch

      - task: CmdLine@2
        displayName: npm install
        inputs:
          script: npm install

      - task: NuGetCommand@2
        displayName: NuGet restore
        inputs:
          command: restore
          restoreSolution: ReactAndroid/packages.config
          feedsToUse: config
          #vstsFeed: # Required when feedsToUse == Select
          #includeNuGetOrg: true # Required when feedsToUse == Select
          nugetConfigPath: ReactAndroid/NuGet.Config
          #externalFeedCredentials: # Optional
          #noCache: false
          #disableParallelProcessing: false
          restoreDirectory: packages/
          verbosityRestore: Detailed # Options: quiet, normal, detailed
          #packagesToPush: '$(Build.ArtifactStagingDirectory)/**/*.nupkg;!$(Build.ArtifactStagingDirectory)/**/*.symbols.nupkg' # Required when command == Push
          #nuGetFeedType: 'internal' # Required when command == Push# Options: internal, external
          #publishVstsFeed: # Required when command == Push && NuGetFeedType == Internal
          #publishPackageMetadata: true # Optional
          #allowPackageConflicts: # Optional
          #publishFeedCredentials: # Required when command == Push && NuGetFeedType == External
          #verbosityPush: 'Detailed' # Options: quiet, normal, detailed
          #packagesToPack: '**/*.csproj' # Required when command == Pack
          #configuration: '$(BuildConfiguration)' # Optional
          #packDestination: '$(Build.ArtifactStagingDirectory)' # Optional
          #versioningScheme: 'off' # Options: off, byPrereleaseNumber, byEnvVar, byBuildNumber
          #includeReferencedProjects: false # Optional
          #versionEnvVar: # Required when versioningScheme == ByEnvVar
          #majorVersion: '1' # Required when versioningScheme == ByPrereleaseNumber
          #minorVersion: '0' # Required when versioningScheme == ByPrereleaseNumber
          #patchVersion: '0' # Required when versioningScheme == ByPrereleaseNumber
          #packTimezone: 'utc' # Required when versioningScheme == ByPrereleaseNumber# Options: utc, local
          #includeSymbols: false # Optional
          #toolPackage: # Optional
          #buildProperties: # Optional
          #basePath: # Optional
          #verbosityPack: 'Detailed' # Options: quiet, normal, detailed
          #arguments: # Required when command == Custom

      - task: CmdLine@1
        displayName: 'npm auth'
        inputs:
          filename: npm
          arguments: 'config set $(publishnpmfeed)/registry/:_authToken $(npmTokenOffice)'

      - task: CmdLine@2
        displayName: Do Publish
        inputs:
          script: node .ado/publish.js

      - task: CmdLine@1
        displayName: 'npm unauth'
        inputs:
          filename: npm
          arguments: 'config set $(publishnpmfeed)/registry/:_authToken XXXXX'

      - template: templates\prep-android-nuget.yml

      - task: NuGetCommand@2
        displayName: 'NuGet pack'
        inputs:
          command: pack
          packagesToPack: 'ReactAndroid/ReactAndroid.nuspec'
          packDestination: '$(System.DefaultWorkingDirectory)'

      - task: NuGetCommand@2
        displayName: 'NuGet push'
        inputs:
          command: push
          packagesToPush: '$(System.DefaultWorkingDirectory)/OfficeReact.Android*.nupkg'
          publishVstsFeed: '86ec7889-a365-4cd1-90df-6e18cc2ea59f'
