name: CI

on: [push, pull_request]

jobs:

  AndroidRNPR:
    name: Android React Native PR

    runs-on: windows-2016
    
    steps:
    - uses: actions/checkout@v1
      submodules: true

    - run: npm install

    - name: Setup Nuget.exe
      uses: warrenbuckley/Setup-Nuget@v1

    - name: NuGet restore
      run: nuget.exe restore ReactAndroid/packages.config -PackagesDirectory packages/ -Verbosity Detailed -NonInteractive

    - name: Create RNTester bundle
      run: node cli.js bundle --entry-file .\RNTester\js\RNTesterApp.android.js --bundle-output RNTesterApp.android.bundle --platform android --reactNativePath .
      
    - run: gradlew.bat "-Pparam=excludeLibs" installArchives

    - name: Extract version from package.json, and put it in nuspec
      run: |
        $lines = Get-Content package.json | Where {$_ -match '^\s*"version":.*'} 
        $npmVersion = $lines.Trim().Split()[1].Trim('",');
        (Get-Content ReactAndroid/ReactAndroid.nuspec).replace('__BuildBuildNumber__', $npmVersion) | Set-Content ReactAndroid/ReactAndroid.nuspec
      shell: powershell

    - name: Change pom file to always use version 1000
      run: |
        (Get-Content android\com\facebook\react\react-native\0.59.0\react-native-0.59.0.pom).replace('<version>0.59.0</version>', '<version>1000.0.0-master</version>') | Set-Content android\com\facebook\react\react-native\0.59.0\react-native-0.59.0.pom
      shell: powershell

    - run: nuget pack ReactAndroid/ReactAndroid.nuspec

    - run: gradlew.bat "clean"