name: CI

on: [pull_request]

jobs:

  AndroidRNPR:
    name: Android React Native PR
    runs-on: windows-2016
    steps:

    - name: Skip NO CI
      if: contains( github.event.head_commit.message, '***NO_CI***')
      run: exit 123

    - uses: actions/checkout@v1
      with:
        submodules: true

    - run: npm install

    - name: Setup Nuget.exe
      uses: warrenbuckley/Setup-Nuget@v1

    - name: NuGet restore
      run: nuget.exe restore ReactAndroid/packages.config -PackagesDirectory ReactAndroid/packages/ -Verbosity Detailed -NonInteractive

    - name: Create RNTester bundle
      run: node cli.js bundle --entry-file .\RNTester\js\RNTesterApp.android.js --bundle-output RNTesterApp.android.bundle --platform android --reactNativePath .
      
    - run: gradlew.bat "-Pparam=excludeLibs" installArchives

    - name: Extract version from package.json, and put it in nuspec
      run: |
        $lines = Get-Content package.json | Where {$_ -match '^\s*"version":.*'} 
        $npmVersion = $lines.Trim().Split()[1].Trim('",');
        (Get-Content ReactAndroid/ReactAndroid.nuspec).replace('__BuildBuildNumber__', $npmVersion) | Set-Content ReactAndroid/ReactAndroid.nuspec
      shell: powershell

    - name: Change pom file to always use version 1000
      run: |
        (Get-Content android\com\facebook\react\react-native\0.59.0\react-native-0.59.0.pom).replace('<version>0.59.0</version>', '<version>1000.0.0-master</version>') | Set-Content android\com\facebook\react\react-native\0.59.0\react-native-0.59.0.pom
      shell: powershell

    - run: nuget pack ReactAndroid/ReactAndroid.nuspec

    - run: gradlew.bat "clean"

  ApplePR:
    name: Apple React Native PR
    runs-on: macOS-latest
    strategy:
      matrix:
        slice: [
          {packager_platform: ios, xcode_sdk: iphonesimulator, xcode_scheme: RNTester, xcode_destination: 'platform=iOS Simulator,OS=latest,name=iPhone 5s' },
          {packager_platform: ios, xcode_sdk: appletvsimulator, xcode_scheme: RNTester-tvOS, xcode_destination: 'platform=tvOS Simulator,OS=latest,name=Apple TV' },
          {packager_platform: macos, xcode_sdk: macosx, xcode_scheme: RNTester-macOS, xcode_destination: 'platform=macOS,arch=x86_64' }
        ]

    steps:

    - name: Skip NO CI
      if: contains( github.event.head_commit.message, '***NO_CI***')
      run: exit 123

    - uses: actions/checkout@v1
      with:
        submodules: true

    - run: brew bundle
